name: Release tarball

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake autopoint gettext git libtool make texinfo g++

    - name: Run autogen
      run: ./autogen.sh

    - name: Configure
      run: |
        export CC=gcc CXX=g++
        ./configure

    - name: Build and Test
      run: make distcheck

    - name: Extract Tag Name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./fswatch-${{ env.TAG_NAME }}.tar.gz
        asset_name: fswatch-${{ env.TAG_NAME }}.tar.gz
        asset_content_type: application/gzip